[package]
name = "number-types"
version = "0.1.0"
edition = "2021"
description = "A typenum clone I made for fun with some positive changes but much fewer features"
license = "MIT"
authors = ["Dellynyaa"]

[dependencies]
